spring:
  application:
    name: voucherengine
  datasource:
    url: jdbc:postgresql://localhost:5432/voucherengine
    username: voucherengine
    password: voucherengine
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.type.json_format_mapper: org.wahlen.voucherengine.config.ToolsJacksonJsonFormatMapper
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
