spring:
  profiles:
    default: development
  application:
    name: voucherengine
  datasource:
    url: jdbc:postgresql://localhost:5432/voucherengine
    username: voucherengine
    password: voucherengine
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.type.json_format_mapper: org.wahlen.voucherengine.config.ToolsJacksonJsonFormatMapper
  threads:
    virtual:
      enabled: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/voucherengine
